services:
  proxy:
    build: proxy/.
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
    networks:
      docker_network:
        ipv4_address: 10.48.81.10

  backend:
    build: backend/.
    ports:
      - 9000:9000
    networks:
      docker_network:
        ipv4_address: 10.48.81.11

  frontend:
    build: proxy/frontend/.

  # database:
  #   build: database/.

networks:
  docker_network:
    ipam:
      driver: default
      config:
        - subnet: 10.48.0.0/16
          ip_range: 10.48.81.0/24
          gateway: 10.48.81.1
