services:
  frontend:
    build: web/.
    ports:
      - 80:80
    networks:
      - backend_network
      - frontend_network

  backend:
    build: backend/.
    ports:
      - 9000:9000
    networks:
      - backend_network
    domainname: backend.local

  # database:
  #   build: database/.



networks:
  backend_network:
  frontend_network:
