FROM python:3.10

EXPOSE 9000

COPY main.py /usr/share/backend
COPY requirements.txt /usr/share/backend



RUN <<EOF
pip install -r requirements.txt
python -m flask --app /usr/share/main.py run -p 9000
EOF
